### PR TITLE
Upgraded to MVC 5.2.3

### PR DESCRIPTION
**Pull request by mwillebrands**

### CODE REVIEW

**Comment by robdmoore** [comment]
You will also need to change the NuSpec file from memory

**Comment by mwillebrands** [comment]
To update the version number?

**Comment by robdmoore** [comment]
yep :)

**Comment by mwillebrands** [comment]
Done!

**Comment by robdmoore** [comment]
I realised that I had made a mistake and hadn't put ASP.NET MVC as a dependency in the nuspec file. That's what I meant when I said bump the version number. The one you bumped we don't ahve to touch because I use gitversion - it happens automatically.

Do you mind adding in this to the nuspec in `<metadata>` and then I'll merge and push out a package:

```xml
    <dependencies>
      <dependency id="Microsoft.AspNet.Mvc" version="5.2.3" />
    </dependencies>
```

**Comment by mwillebrands** [comment]
Done!

**Comment by robdmoore** [comment]
Thanks. Pushed to Nuget 1.0.1

**Pull request merged**
